api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    eager_loading:
        enabled: true

    collection:
        pagination:
          items_per_page: 10
          maximum_items_per_page: 20
    exception_to_status:
        App\Exception\UserAlreadyHasServiceRegisteredException: 404